from src.Objects.GameObjects import Board
board = Board()
board.setup()
pawn = board.select(1, 1)
selection = board.select(1, 3)
board.move(pawn, selection)
rock = board.select(2, 0)
board.update()
print('Knight')
print(rock.possible_moves(white=board.coord_white, black=board.coord_black))
selection = board.select(3, 1)
board.move(rock, selection)
#print('Pawn')
#print(pawn.possible_moves(white=board.coord_white, black=board.coord_black))
print(board)
